[metadata]
name = plover-mussel-power
version = 0.1.1
description = System and dictionaries for Mussel Power
author = Harry W
author_email = StenoHarri@gmail.com
license = GNU General Public License v2 or later (GPLv2+)
url = https://github.com/StenoHarri/plover_mussel_power
keywords = plover plover_plugin
long_description = file: README.md
long_description_content_type = text/markdown

[options]
zip_safe = True
setup_requires =
    setuptools>=30.3.0
packages =
    plover_mussel_power
install_requires = #Honestly I'm just copying plover-controller
    plover[gui_qt]>=4.0.0.dev10
    PySDL2
    pysdl2-dll;platform_system!='Linux'
    plover-python-dictionary #For pseudo_steno

include_package_data = True

[options.entry_points]
plover.system =
	Mussel Power = plover_mussel_power.system
